swagger: '2.0'
info:
  title: OPTEAMA AP Wifi API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /wifi/ap/:
    get:
      tags: [AP]
      operationId: ap.get_all
      summary: Get all AP in all the sites
      responses:
        200:
          description: Return list of AP
          schema:
            type: array
            items:
              $ref: '#/definitions/AP'
        404:
          description: Organization not found
    post:
      tags: [AP]
      operationId: ap.create_multiple
      summary: Deploy multiple AP
      parameters:
        - name: ap_list
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/AP'
      responses:
        200:
          description: APs created
        403:
          description: APs creation failed
  /wifi/ap/{site}:
    get:
      tags: [AP]
      operationId: ap.get_by_site
      summary: Get all AP within a site
      parameters:
        - $ref: '#/parameters/Site'
      responses:
        200:
          description: Return list of AP
          schema:
            $ref: '#/definitions/AP'
        404:
          description: Site not found
    post:
      tags: [AP]
      operationId: ap.create
      summary: Deploy an AP in a site
      parameters:
        - $ref: '#/parameters/Site'
        - name: ap
          in: body
          schema:
            $ref: '#/definitions/AP'
      responses:
        200:
          description: AP created
        403:
          description: AP creation failed
    put:
      tags: [AP]
      operationId: ap.update
      summary: Update an AP in a site
      parameters:
        - $ref: '#/parameters/Site'
        - name: ap
          in: body
          schema:
            $ref: '#/definitions/AP'
      responses:
        200:
          description: AP updated
        403:
          description: AP update failed
  /wifi/ap/{site}/{serial}:
    get:
      tags: [AP]
      operationId: ap.get_by_serial
      summary: Get AP defined by serial within a site
      parameters:
        - $ref: '#/parameters/Site'
        - $ref: '#/parameters/Serial'
      responses:
        200:
          description: Return AP
          schema:
            $ref: '#/definitions/AP'
        404:
          description: AP not found
    delete:
      tags: [AP]
      operationId: ap.remove
      summary: Remove an AP from a site
      parameters:
        - $ref: '#/parameters/Site'
        - $ref: '#/parameters/Serial'
      responses:
        200:
          description: AP removed
        403:
          description: AP removal failed

parameters:
  Site:
    name: site
    description: Site names
    in: path
    type: string
    required: true
    enum: [TLS, MRG, SNZ, MLT, RCF]
  Serial:
    name: serial
    description: Serials
    in: path
    type: string
    required: true
definitions:
  AP:
    type: object
    required:
      - site
      - building
      - floor
      - serial
    properties:
      name:
        type: string
        description: AP's name
        example: "TLS-AP-SKP-1c-3"
        pattern: "^[A-Z]{3}-AP-[A-Z]{3}-[A-Za-z0-9]{1,3}-[0-9]{1,3}$"
        minLength: 14
        maxLength: 18
      site:
        type: string
        enum: [TLS, MRG, SNZ, MLT, RCF]
        description: Site's name
        example: "TLS"
      building:
        type: string
        description: Building's name
        example: "SKP"
        minLength: 3
        maxLength: 3
      floor:
        type: string
        description: Floor's name
        example: "1c"
        minLength: 1
        maxLength: 3
      lat:
        type: string
        description: Latitude
        example: "3.4743636"
        minLength: 6
        maxLength: 10
      lng:
        type: string
        description: Longitude
        example: "40.3743194"
        minLength: 6
        maxLength: 10
      serial:
        type: string
        description: Unique identifier
        example: "Q2xx-xxxx-xxxx"
        pattern: "^Q2[0-9A-Za-z-]{2}-[0-9A-Za-z-]{4}-[0-9A-Za-z-]{4}$"
        readOnly: true
